apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader-service
spec:
  selector:
    matchLabels:
      app: uploader-service
  template:
    metadata:
      labels:
        app: uploader-service
    spec:
      containers:
      - name: uploader-service
        image: sujalphuse/linkedin-app-uploader-service.0.0.2
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "100m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s

          - name: GCLOUD_STORAGE_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: my-secret-linkedin
                key: GCLOUD_BUCKET_NAME
          
          - name: GCLOUD_STORAGE_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-secret-linkedin
                key: GCLOUD_ACCESS_KEY
        ports:
        - containerPort: 9050

---

apiVersion: v1
kind: Service
metadata:
  name: uploader-service
spec:
  selector:
    app: uploader-service
  ports:
  - port: 80
    targetPort: 9050
