spring.application.name: uploader-service

server.servlet.context-path: /uploads
server.port: 9050

eureka.client.service-url.defaultZone:  http://localhost:8761/eureka

cloudinary:
  cloud-name: dcoxhefhh
  api-key: 145676925257171
  api-secret: VF2fGT4YLuRpHBQBvU9suQ2-b3w

gcloud:
  storage-bucket-name: ${GCLOUD_STORAGE_BUCKET_NAME} #storage-linkedin
  storage-access-key: ${GCLOUD_STORAGE_ACCESS_KEY}