spring.application.name: uploader-service

server.servlet.context-path: /uploads
server.port: 9050

eureka.client.service-url.defaultZone:  http://localhost:8761/eureka

cloudinary:
  cloud-name: dcoxhefhh
  api-key: 145676925257171
  api-secret: VF2fGT4YLuRpHBQBvU9suQ2-b3w

gcloud:
  storage-bucket-name: storage-linkedin
  storage-access-key: >
    {
      "type": "service_account",
      "project_id": "linkedin-project-462709",
      "private_key_id": "87a316d1680cf60053666b21b88916a8fac8beda",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC0YZb3xqThXqZv\nUQ4knse6WEE9OF24udS3q15WjG+j24BZGOX+d7cEGItQGwqLJv/qjkFOdnEJ80jM\n6qB4zsBfROLjSIQUOLlU7nxkVb4l4ejvB7TfxoT9vng/r2ElZQ2irNbXfq5eGBJR\nwQC3Ml476pPB+nqrO6lWKOpWAdp+nElqeIsfr/G1PV4HSsc9xmDgCEwzgA95d0ki\nEQZ0juxaBVBIwPf5ksJFxZugAVxz40y/RqKHxYm4Z1D9i2G8lD7ev0dnjFR1lzvC\nn7ZIhtgsR/rT33ciJr7DjPWh4Fq3E4uR5zJsDrokM1R//M/J0V00whPnAfyy0+Cy\n1befWoHXAgMBAAECggEAC8yvVNYo8fzk/La74cDyGHyTCIQce6vKm8/CWLRQYGUk\nGW/04MB15VJ7Ie79MaYaYf6AsQBYUoDPRUMx4td9NZ4zw1iM0ZRkDhniPoQAge4H\ndLG3k6Ai7WmB6F26rOafTaaO7B6Mi1UL7AWWky5y8cW45tOa3Mv0rHXVcChxT1WP\nQt3LMGE9lZ/pyRZQSssyFQ/OukcvfZ1utG/x5EAEXGjLcHEZxmbwLPaUpGzdVjKy\nVID7vaag5eglIJI/314JR0auAtukOYlAZ5u+iAFPeRu8DpDVewM59ctKzzuxY7ox\nHPSJ6v3BF0O9QLVWKFSi6wtd+gQKG8dTWYE7+f85aQKBgQD9eN6UR11vLIUfKb3Q\nXu82DzWR1Woqk4gKcwLRPTPh3OdUfsjAuZX3enA/Q/jt/lM4pJnpGM4+goaKSwgo\nox+Yg3v8J9mROxnhP6ttpg5DjL+vdYPtMJCpMnrFXkD4SRiFL26VFmP2cyPxsM4W\n1rrglYcD08ZTDE/WaYuVmhLiTwKBgQC2Lh1MbT7ps/qK35M0AvobixZqAPzFvlGR\nH4KY5MAdIe/Lgi18Nh8yIbdkjG5aRaK/AxCEpGSCMDLFQ5ic2YP3ZnHbucIc4QsK\n2ANGySH8x0xfuMe/RPGbVH0N2Z3WXrOcm9xF0kSZ1tgIr7HjkTCXviz0xXQ9LEne\n5H7CbOOt+QKBgQCv9RNWjgAPqDE1g+2P1AdtWLuQZD2SFt5umo6PIFR+67HvFyBX\nob24kdeQI6iP1miBPsrVZPHvtP6ezB160FqjrksIrcU8K3H4yxE/SfJG9FMxA3w0\n0Ozrd+6ASsEBWwTZmCbE+kkkkaOXKWy3sBMEyuhyQLZBep+FsblDfjSzwwKBgD4u\ndT+d1ihsjuqRryvEjFuUWL0rwxs3f526FJhdE5md+LwMnbvUuUciLPd72zqipA7w\nW9X6SngJPXsJPHDk6V8rL1ehCrlSsrMr0cp6YkhmOhI9/qexP4oWB20PxwjhYArn\nRALs5w9fPnOQjHYxG1XfynZtYuRyVnBmq0FvazL5AoGAUSL/1tT8LwWWGDtHLgb0\nPs8Ewp0FThZaUb3OmIuhOUd8arXwJKN88CEYR1m5GUUJ72zIjAyke8hhtSltEb0b\nloYLMfl/Xb85VP9ei+WbED/2qglnc4iuVGWdwdqrNSNzXAAkiiU7FtgMfs2W2p9f\nfmB/jKhXlohQWQHDq6pPHrA=\n-----END PRIVATE KEY-----\n",
      "client_email": "project-access-acc@linkedin-project-462709.iam.gserviceaccount.com",
      "client_id": "109683805775828523112",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/project-access-acc%40linkedin-project-462709.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }